# version: "3.11"

# services:
#   neo4j:
#     image: neo4j:5.22
#     container_name: neo4j-local
#     ports:
#       - "7474:7474"         # HTTP UI
#       - "7687:7687"         # Bolt
#     environment:
#       NEO4J_AUTH: "neo4j/your_password"      # <-- change this
#       NEO4J_server_memory_pagecache_size: 1G
#       NEO4J_server_memory_heap_max__size: 1G
#     volumes:
#       - neo4j-data:/data

#   app:
#     build: .
#     container_name: policy-qa-app
#     depends_on:
#       - neo4j
#     ports:
#       - "8501:8501"
#     env_file: .env                      # OPENAI_API_KEY, models, etc.
#     environment:
#       # Point your code at the containerized Neo4j
#       NEO4J_URI: "bolt://neo4j-local:7687"
#       NEO4J_USER: "neo4j"
#       NEO4J_PASSWORD: "password"  # <-- match above
#       # Optional: where your code expects index/policy files
#       DATA_DIR: /app/data
#       INDEX_DIR: /app/data/index
#       POLICY_DIR: /app/data/policies
#     volumes:
#       # keep artifacts and policies on host so you can edit/rebuild locally
#       - ./data:/app/data

# volumes:
#   neo4j-data:


# # services:
# #   neo4j:
# #     image: neo4j:5.22
# #     container_name: neo4j-local
# #     ports:
# #       - "7474:7474"
# #       - "7687:7687"
# #     environment:
# #       NEO4J_AUTH: "neo4j/your_password"
# #       NEO4J_server_memory_pagecache_size: 1G
# #       NEO4J_server_memory_heap_max__size: 1G
# #     volumes:
# #       - neo4j-data:/data
# # volumes:
# #   neo4j-data:


services:
  app:
    build: .
    container_name: policy-qa-app
    ports:
      - "8501:8501"
    environment:
      # OpenAI/LLM
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CHAT_MODEL: gpt-4o-mini
      EMBED_MODEL: text-embedding-3-small
      WHISPER_MODEL: whisper-1
      # Neo4j (Aura or local)
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      NEO4J_DATABASE: ${NEO4J_DATABASE:-neo4j}
      # index paths (match what qa.py defaults to)
      INDEX_PATH: data/index/vector.index
      META_PATH:  data/index/meta.pkl
    volumes:
      - ./data:/app/data           # so index survives rebuilds
      - ./policies:/app/policies   # live-edit policies if you want
    depends_on:
      - neo4j
    # remove depends_on if using Neo4j Aura (managed)

  neo4j:   # only if you run local Neo4j (not Aura)
    image: neo4j:5.22
    container_name: neo4j-local
    ports: ["7474:7474","7687:7687"]
    environment:
      NEO4J_AUTH: "neo4j/your_password"
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data:
