services:
  neo4j:
    image: neo4j:5.22
    container_name: neo4j-local
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/your_password"
      NEO4J_server_memory_pagecache_size: 1G
      NEO4J_server_memory_heap_max__size: 1G
    volumes:
      - neo4j-data:/data
volumes:
  neo4j-data: